/* crypto/elgamal/elgamal_err.c */
/* ====================================================================
 * Copyright (c) 1999-2006 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.OpenSSL.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@OpenSSL.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.OpenSSL.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

/* NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

/*
 * This package is written by Vincent Huang (winscar@stu.xidian.edu.cn)
 * as a tool to do experiments. It can be freely used by anyone.
 * But it is not strong or secure enough to sustain comercial usage.
 * Hope you all happy to use this :-) */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/elgamal.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

#define ERR_FUNC(func) ERR_PACK(ERR_LIB_ElGamal,func,0)
#define ERR_REASON(reason) ERR_PACK(ERR_LIB_ElGamal,0,reason)

static ERR_STRING_DATA ElGamal_str_functs[]=
	{
{ERR_FUNC(ElGamal_F_D2I_ElGamal_SIG),	"d2i_ElGamal_SIG"},
{ERR_FUNC(ElGamal_F_DO_ElGamal_PRINT),	"DO_ElGamal_PRINT"},
{ERR_FUNC(ElGamal_F_ElGamalPARAMS_PRINT),	"ElGamalparams_print"},
{ERR_FUNC(ElGamal_F_ElGamalPARAMS_PRINT_FP),	"ElGamalparams_print_fp"},
{ERR_FUNC(ElGamal_F_ElGamal_DO_SIGN),	"ElGamal_do_encrypt"},
{ERR_FUNC(ElGamal_F_ElGamal_DO_VERIFY),	"ElGamal_do_decrypt"},
{ERR_FUNC(ElGamal_F_ElGamal_NEW_METHOD),	"ElGamal_new_method"},
{ERR_FUNC(ElGamal_F_ElGamal_PARAM_DECODE),	"ElGamal_PARAM_DECODE"},
{ERR_FUNC(ElGamal_F_ElGamal_PRINT_FP),	"ElGamal_print_fp"},
{ERR_FUNC(ElGamal_F_ElGamal_PRIV_DECODE),	"ElGamal_PRIV_DECODE"},
{ERR_FUNC(ElGamal_F_ElGamal_PRIV_ENCODE),	"ElGamal_PRIV_ENCODE"},
{ERR_FUNC(ElGamal_F_ElGamal_PUB_DECODE),	"ElGamal_PUB_DECODE"},
{ERR_FUNC(ElGamal_F_ElGamal_PUB_ENCODE),	"ElGamal_PUB_ENCODE"},
{ERR_FUNC(ElGamal_F_ElGamal_SIGN),	"ElGamal_encrypt"},
{ERR_FUNC(ElGamal_F_ElGamal_SIGN_SETUP),	"ElGamal_encrypt_setup"},
{ERR_FUNC(ElGamal_F_ElGamal_SIG_NEW),	"ElGamal_SIG_new"},
{ERR_FUNC(ElGamal_F_ElGamal_VERIFY),	"ElGamal_decrypt"},
{ERR_FUNC(ElGamal_F_I2D_ElGamal_SIG),	"i2d_ElGamal_SIG"},
{ERR_FUNC(ElGamal_F_OLD_ElGamal_PRIV_DECODE),	"OLD_ElGamal_PRIV_DECODE"},
{ERR_FUNC(ElGamal_F_PKEY_ElGamal_CTRL),	"PKEY_ElGamal_CTRL"},
{ERR_FUNC(ElGamal_F_PKEY_ElGamal_KEYGEN),	"PKEY_ElGamal_KEYGEN"},
{ERR_FUNC(ElGamal_F_SIG_CB),	"SIG_CB"},
{0,NULL}
	};

static ERR_STRING_DATA ElGamal_str_reasons[]=
	{
{ERR_REASON(ElGamal_R_BAD_Q_VALUE)           ,"bad q value"},
{ERR_REASON(ElGamal_R_BN_DECODE_ERROR)       ,"bn decode error"},
{ERR_REASON(ElGamal_R_BN_ERROR)              ,"bn error"},
{ERR_REASON(ElGamal_R_DATA_TOO_LARGE_FOR_KEY_SIZE),"data too large for key size"},
{ERR_REASON(ElGamal_R_DECODE_ERROR)          ,"decode error"},
{ERR_REASON(ElGamal_R_INVALID_DIGEST_TYPE)   ,"invalid digest type"},
{ERR_REASON(ElGamal_R_MISSING_PARAMETERS)    ,"missing parameters"},
{ERR_REASON(ElGamal_R_MODULUS_TOO_LARGE)     ,"modulus too large"},
{ERR_REASON(ElGamal_R_NO_PARAMETERS_SET)     ,"no parameters set"},
{ERR_REASON(ElGamal_R_PARAMETER_ENCODING_ERROR),"parameter encoding error"},
{0,NULL}
	};

#endif

void ERR_load_ElGamal_strings(void)
	{
#ifndef OPENSSL_NO_ERR

	if (ERR_func_error_string(ElGamal_str_functs[0].error) == NULL)
		{
		ERR_load_strings(0,ElGamal_str_functs);
		ERR_load_strings(0,ElGamal_str_reasons);
		}
#endif
	}
